language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war


after success:
  - mkdir codedeploy
  - zip -r csye6225-fall2017-war.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye6225-fall2017-war.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIX2KCXBF4KLND4VA
    secret_access_key:
      secure: "SNGssPJRaIbIy0wxS3meTQOk+EFHoR1Vjp3s8xHl/GIdN7ajE4mOpaxh/52G5pzPfUWHRjtPnkw2+7BmJj0SrGwj7nbXbP36xi1GKt+dYNVVrW92eA/m0dYoxO9jtfHpX2ZAuJOND65oEknqyp7HoLNtiz67ETWSTlIpLkGwf7DaOdN2pkiZuGizTHYbwFqcPqlqrEKfJRMqdgCmfAlvN3h04KAs3sy094th9VZZqGZFa3prARH/gUl5QlNk0c3RcEWiHTqWK2j9hjTRTvyQVfZBmVzVqHTeZNp9viSN4S6EbZXiA/KhBqk1IVmwWhKjlx44xJYsC+LukY8qeIJBPgbcrMWoIbPQlnfpkjK5AvEZvHERPEKsPVELUU/2eC880xv/5W0VbB7Aijobcw4cIMYJlLo6Uccz0rU1iRyS/4RLD3rpQ37SHzqUKHfGjDniJA79nBv/reQpR6xc7HmePmkutbO2sjkqGPI/Szg7F/vuRprHY0wLfcyQ6PxJ7dk2Xyhsu2kcMsEg02x0mJ/KCj83EnWpqfHV6n5p1qAc+cJOybgXI+vw1snRuuXt9qRZRzOseTs3QAxpVi5TVVG90om8xOH6Gc+B6gGIy6hVYCE5ACpEcFbhVH8kFU7G2EvpbY2Q+be60bvP+Pnyx74j7bCBLq9OyEXzvx/q5AhpW8Q="
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-kunchea.me
    region: us-east-1
    skip_cleanup: true
    on:
      all-branches: true
  - provider: codedeploy
    access_key_id: AKIAIX2KCXBF4KLND4VA
    bucket: code-deploy.csye6225-fall2017-kunchea.me
    key: csye6225-fall2017-war.zip
    bundle_type: zip
    application: csye6225-fall2017-war
    deployment_group: csye6225-fall2017-war
    region: us-east-1
    secret_access_key:
      secure: "SNGssPJRaIbIy0wxS3meTQOk+EFHoR1Vjp3s8xHl/GIdN7ajE4mOpaxh/52G5pzPfUWHRjtPnkw2+7BmJj0SrGwj7nbXbP36xi1GKt+dYNVVrW92eA/m0dYoxO9jtfHpX2ZAuJOND65oEknqyp7HoLNtiz67ETWSTlIpLkGwf7DaOdN2pkiZuGizTHYbwFqcPqlqrEKfJRMqdgCmfAlvN3h04KAs3sy094th9VZZqGZFa3prARH/gUl5QlNk0c3RcEWiHTqWK2j9hjTRTvyQVfZBmVzVqHTeZNp9viSN4S6EbZXiA/KhBqk1IVmwWhKjlx44xJYsC+LukY8qeIJBPgbcrMWoIbPQlnfpkjK5AvEZvHERPEKsPVELUU/2eC880xv/5W0VbB7Aijobcw4cIMYJlLo6Uccz0rU1iRyS/4RLD3rpQ37SHzqUKHfGjDniJA79nBv/reQpR6xc7HmePmkutbO2sjkqGPI/Szg7F/vuRprHY0wLfcyQ6PxJ7dk2Xyhsu2kcMsEg02x0mJ/KCj83EnWpqfHV6n5p1qAc+cJOybgXI+vw1snRuuXt9qRZRzOseTs3QAxpVi5TVVG90om8xOH6Gc+B6gGIy6hVYCE5ACpEcFbhVH8kFU7G2EvpbY2Q+be60bvP+Pnyx74j7bCBLq9OyEXzvx/q5AhpW8Q="
    wait-until-deployed: true
notifications:
  email:
    recipients:
      - kunche.a@husky.neu.edu
      - nakhawa.a@husky.neu.edu
      - chaudhari.k@husky.neu.edu
      - saxena.pr@husky.neu.edu

  services: mysql
