language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war


after success:
  - sudo mkdir codedeploy
  

before deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIAUVK7GBA3D3HSCA
    secret_access_key:
      secure: 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
    local_dir: codedeploy
    bucket: csye6225-fall2017-nakhawaa.me.bucket
    region: us-east-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAIAUVK7GBA3D3HSCA
    bucket: csye6225-fall2017-nakhawaa.me.bucket
    key: csye6225-fall2017-war.zip
    bundle_type: zip
    application: csye6225-fall2017-war
    deployment_group: csye6225-fall2017-war
    region: us-east-1
    secret_access_key:
      secure: 6gLP/hAp2C0E2HRQXFlT90iniYT8Lv53JiE/H0mB
    wait-until-deployed: true
    
notifications:
  email:
    recipients:
      - kunche.a@husky.neu.edu
      - nakhawa.a@husky.neu.edu
      - chaudhari.k@husky.neu.edu
      - saxena.pr@husky.neu.edu

  services: mysql
