language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r MyProject.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd..

deploy:
  - provider: s3
    access_key_id: AKIAIJ3X7K3O2QBWGR6A
    secret_access_key:
      secure: NJWEgMN2bQ05uGiEEOJ6lIjEzSErnoPFLip4D+WhMaTZIfYENIc+QGbGBnHIlp6P/X0LjQovPIQVayB9ZGVdzw4nKMeWExu/AKHFrlS+IBNyK1M+Tglb2O/gH3v/NPQwh9vtSsQS8YK968fL/tfEhMyxTEPeJBSsjjWfNBllwhFA91KTu4g4BV5I7JB5/WTh5DxE6Z5xviuh/F0qQf6bp+Vp+aLFr1pb80vAxOfPLLWJRpSP6o7ATjo+1122kNueI/8J0anO38h5Quz1eWvZQSWoIGE//61W5I+KKu9L7SsAe4H06h/xTKjlaloMjlf5SGt/dJHCfALTKUm5P+8YB0SX824lZSfJ2LirauPGJDKvi0QfrBlnd7hX8+cZzUGomVH0CiWLHj0TJpT8P/tfUqKAMfbNHMx1M2E4pLtefwy5R0bTM/wXvAvWwy4Nh7+Mv3UMag18ukp6f8ib3fegPMWTVLfHVBEvhteiyiWm8t+hetkj4+ac3wM08yCFbbLASsuM2wNpWln+IjtHAicCqNUruekcgRFMifHCjzs0wwKTvigZuWdSajFmlHQPVLjwGs8ATFkteEw+HP9yeWb7W31L9iFoqvqZwL8BTSPDl92k7ltvfQ4m3lKQtchVXFTz36JilXzjBY5ShnHz/Uom9JddQw0dQrDDzGiI4Wclc1I=
    local_dir: codedeploy
    bucket: code-deploy.csye6225-fall2017-saxenapr.me
    region: us-east-1
    skip_cleanup: true

notifications:
  email:
    recipients:
      - kunche.a@husky.neu.edu
      - nakhawa.a@husky.neu.edu
      - chaudhari.k@husky.neu.edu
      - saxena.pr@husky.neu.edu

services: mysql

