language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war


after_success:
  - mkdir -p codedeploy
  - zip -r csye6225-fall2017-war.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye6225-fall2017-war.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIX2KCXBF4KLND4VA
    secret_access_key:
      secure: 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
    local_dir: codedeploy
    bucket: csye6225-fall2017-kunchea.me.bucket
    region: us-east-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAIX2KCXBF4KLND4VA
    bucket: csye6225-fall2017-kunchea.me.bucket
    key: csye6225-fall2017-war.zip
    bundle_type: zip
    application: csye6225
    deployment_group: csye6225
    region: us-east-1
    secret_access_key:
      secure: 4XJa1a3I6BD5pqze6ZuBrD1XVTvAWrmQT5F9LMY8
    wait-until-deployed: true
    
notifications:
  email:
    recipients:
      - kunche.a@husky.neu.edu
      - nakhawa.a@husky.neu.edu
      - chaudhari.k@husky.neu.edu
      - saxena.pr@husky.neu.edu

  services: mysql
