language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war


after_success:
	  - mkdir codedeploy
	  - zip -r csye6225-fall2017-war.zip build/libs/ROOT.war appspec.yml restartTomcat.sh infrastructure/aws/cloudwatch/awslogs.conf
	  - ls -al
	  - mv csye6225-fall2017-war.zip ubuntu/
	  - ls -al
	  - pwd
	  - cd ubuntu
	  - ls -al
	  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAJ75553KXEXZZYPRQ
    secret_access_key: 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
    local_dir: codedeploy
    bucket: csye6225-fall2017-kunchea.me.bucket
    region: us-east-1
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: AKIAJ75553KXEXZZYPRQ
    bucket: csye6225-fall2017-kunchea.me.bucket
    key: csye6225-fall2017-war.zip
    bundle_type: zip
    application: csye6225
    deployment_group: csye6225
    region: us-east-1
    secret_access_key: fPMDdR0lxm7xVC69L/G97Onm7OXuT2MCfikz4oEL
    wait-until-deployed: true
    
notifications:
  email:
    recipients:
      - kunche.a@husky.neu.edu
      - nakhawa.a@husky.neu.edu
      - chaudhari.k@husky.neu.edu
      - saxena.pr@husky.neu.edu

  services: mysql
